% Run this script
classdef GUI<handle
    properties (Access=private)
        RunWindow
        GenPanel, SolvePanel
        % Generation panel attributes
        GenSubPanelSizes, GenSubPanelStartPose
        GenVizCheckBox
        GenButton, StopButton
        HeigthTextArea, WidthTextArea, GenStartRow, GenStartCol
        HeightLabel, WidthLabel, SProwLabel, SPcolLabel
        % Solving panel attributes
        SolveSubPanelStart, SolveSubPanelGoal
        SolveVizCheckBox
        SolveButton, SolveStopButton
        StRowTextArea, StColTextArea, GoalRow, GoalCol
        StRowLabel, StColLabel, GoalRowLabel, GoalColLabel
       
    end
    properties (Access=public) 
        DefaultFigPose = [480, 200, 820, 580]; 
    end
    methods
            function obj = GUI()
               
                InitMainWindow(obj);
                CreateGenerationPanel(obj)
                CreateSolvingPanel(obj);
              
               
            end
        end  
    methods (Access=private)
            function InitMainWindow(obj) % creates the Run Window
                obj.RunWindow  = uifigure('Name', 'Maze Generator-Solver',...
                      'Position', obj.DefaultFigPose, ...
                      'AutoResizeChildren',  'off', ...
                      'WindowButtonMotionFcn', @(src, event)obj.WindowSize());
            end 

            function CreateGenerationPanel(obj) % creates the Generation panel

                obj.GenPanel = uipanel('Parent',obj.RunWindow, ...
                       'Title', 'Generatation panel', ...
                       'Position',[10, obj.DefaultFigPose(4) - 210, (obj.DefaultFigPose(3)-30)/2,  200], ...
                       'TitlePosition', 'centertop', ...
                       'FontSize', 14, ...
                       'FontWeight', 'bold', ...
                       'BackgroundColor','white');      
               obj.GenSubPanelSizes = uipanel('Parent',  obj.GenPanel, ...
                       'Title', 'Maze sizes', ...
                       'Position',[120, 90, 130,  80], ...
                       'TitlePosition', 'centertop', ...
                       'FontSize', 14, ...
                       'FontWeight', 'bold', ...
                       'BackgroundColor','white');
                obj.GenSubPanelStartPose = uipanel('Parent',  obj.GenPanel, ...
                       'Title', 'Start Pose', ...
                       'Position',[120, 5, 130,  80], ...
                       'TitlePosition', 'centertop', ...
                       'FontSize', 14, ...
                       'FontWeight', 'bold', ...
                       'BackgroundColor','white');
               obj.GenButton = uibutton(obj.GenPanel, 'Text', 'Generate', ...
                    'Position',[20,60,70, 50], ...
                    'FontWeight', 'bold', ...
                    'FontSize', 14);

              obj.HeigthTextArea  = uitextarea(obj.GenSubPanelSizes , 'Value', '1', ...
                       'Position', [10, 10, 40, 25], ...
                       'FontSize', 14); 
                obj.HeightLabel = uilabel( obj.GenSubPanelSizes,  'Position', [10, 32, 50, 25], 'Text', 'Height', 'FontSize', 14);


                obj.WidthTextArea  = uitextarea(obj.GenSubPanelSizes , 'Value', '1', ...
                       'Position', [65, 10, 40, 25], ...
                       'FontSize', 14); 
               obj.WidthLabel = uilabel( obj.GenSubPanelSizes,  'Position', [65, 32, 50, 25], 'Text', 'Width', 'FontSize', 14);
               obj.GenStartRow =    uitextarea(obj.GenSubPanelStartPose , 'Value', '1', ...
                       'Position', [10, 10, 40, 25], ...
                       'FontSize', 14); 
              obj.SProwLabel = uilabel(obj.GenSubPanelStartPose,  'Position', [10, 32, 50, 25], 'Text', 'Row', 'FontSize', 14);
              obj.GenStartCol =  uitextarea(obj.GenSubPanelStartPose , 'Value', '1', ...
                       'Position', [65, 10, 40, 25], ...
                       'FontSize', 14); 
              obj.SPcolLabel = uilabel(obj.GenSubPanelStartPose,  'Position', [65, 32, 50, 25], 'Text', 'Column', 'FontSize', 14);
              obj.GenVizCheckBox =uicheckbox(obj.GenPanel, 'Text', 'Vizualization', ...
                    'Position',[275,100,150, 50], ...
                    'FontWeight', 'bold', ...
                    'FontSize', 14);
             obj.StopButton = uibutton(obj.GenPanel, 'Text', 'STOP', ...
                    'Position',[300,30,60, 60], ...
                    'FontWeight', 'bold', ...
                    'FontSize', 14);

            end


            function  CreateSolvingPanel(obj)  % creates the Solving panel
                  obj.SolvePanel = uipanel('Parent',obj.RunWindow, ...
                       'Title', 'Solving panel', ...
                       'Position',[20+obj.GenPanel.Position(3), obj.DefaultFigPose(4) - 210, obj.GenPanel.Position(3), 200], ...
                       'TitlePosition', 'centertop', ...
                       'FontSize', 14, ...
                       'FontWeight', 'bold', ...
                       'BackgroundColor','white');


                    obj.SolveSubPanelStart = uipanel('Parent',   obj.SolvePanel, ...
                       'Title', 'Start Cell', ...
                       'Position',[120, 90, 130,  80], ...
                       'TitlePosition', 'centertop', ...
                       'FontSize', 14, ...
                       'FontWeight', 'bold', ...
                       'BackgroundColor','white');
                obj.SolveSubPanelGoal = uipanel('Parent',  obj.SolvePanel, ...
                       'Title', 'Goal Cell', ...
                       'Position',[120, 5, 130,  80], ...
                       'TitlePosition', 'centertop', ...
                       'FontSize', 14, ...
                       'FontWeight', 'bold', ...
                       'BackgroundColor','white');
               obj.SolveButton = uibutton( obj.SolvePanel, 'Text', 'Solve', ...
                    'Position',[20,60,70, 50], ...
                    'FontWeight', 'bold', ...
                    'FontSize', 14);

              obj.StRowTextArea  = uitextarea(obj.SolveSubPanelStart , 'Value', '1', ...
                       'Position', [10, 10, 40, 25], ...
                       'FontSize', 14); 
                obj.StRowLabel = uilabel(obj.SolveSubPanelStart,  'Position', [10, 32, 50, 25], 'Text', 'Row', 'FontSize', 14);


                obj.StColTextArea  = uitextarea(obj.SolveSubPanelStart  , 'Value', '1', ...
                       'Position', [65, 10, 40, 25], ...
                       'FontSize', 14); 
               obj.StColLabel = uilabel(obj.SolveSubPanelStart,  'Position', [65, 32, 50, 25], 'Text', 'Column', 'FontSize', 14);


              obj.GoalRow =    uitextarea(obj.SolveSubPanelGoal , 'Value', '1', ...
                       'Position', [10, 10, 40, 25], ...
                       'FontSize', 14); 
              obj.GoalRowLabel = uilabel(  obj.SolveSubPanelGoal ,  'Position', [10, 32, 50, 25], 'Text', 'Row', 'FontSize', 14);
              obj.GoalCol=  uitextarea(  obj.SolveSubPanelGoal  , 'Value', '1', ...
                       'Position', [65, 10, 40, 25], ...
                       'FontSize', 14); 
              obj.GoalColLabel = uilabel(  obj.SolveSubPanelGoal ,  'Position', [65, 32, 50, 25], 'Text', 'Column', 'FontSize', 14);
              obj.SolveVizCheckBox =uicheckbox(obj.SolvePanel , 'Text', 'Vizualization', ...
                    'Position',[275,100,150, 50], ...
                    'FontWeight', 'bold', ...
                    'FontSize', 14);
             obj.SolveStopButton = uibutton(obj.SolvePanel , 'Text', 'STOP', ...
                    'Position',[300,30,60, 60], ...
                    'FontWeight', 'bold', ...
                    'FontSize', 14);

            end

            
            function WindowSize(obj) % Update panels sizes
                 obj.GenPanel.Position  = [10, obj.RunWindow.Position(4) - 210, (obj.RunWindow.Position(3)-30)/2, 200]; 
                 obj.SolvePanel.Position =  [20+obj.GenPanel.Position(3), obj.RunWindow.Position(4) - 210,  obj.GenPanel.Position(3), 200];
            end 
               
            end 
 end 
       

