
% Run this script
classdef GUI<handle
    properties (Access=private)
        RunWindow
        GenPanel, SolvePanel
        % Generation panel attributes
        GenSubPanelSizes, GenSubPanelStartPose
        GenVizCheckBox
        GenButton, StopButton
        HeigthTextArea, WidthTextArea, GenStartRow, GenStartCol
        HeightLabel, WidthLabel, SProwLabel, SPcolLabel
        % Solving panel attributes
        SolveSubPanelStart, SolveSubPanelGoal
        SolveVizCheckBox
        SolveButton, SolveStopButton
        StRowTextArea, StColTextArea, GoalRow, GoalCol
        StRowLabel, StColLabel, GoalRowLabel, GoalColLabel
       
    end
    properties (Access=public) 
        DefaultFigPose = [480, 200, 820, 580]; 
        DefaultSizeLimits = [1 100]
        GenMaze = InitMaze(1, 1, [1,1]);
        SolvedMazeBut
        % Maze sizes
        Height, Width;
        % Start Pose = [row, col]
        GenStartPose = [0, 0];
        isVizualizeGen = false;
    end
    methods
            function obj = GUI()
               
                InitMainWindow(obj);
                InitGenParameters(obj);
                CreateGenerationPanel(obj)
                CreateSolvingPanel(obj);
              
               
            end
        end  
    methods (Access=private)
            function InitMainWindow(obj) % creates the Run Window
                obj.RunWindow  = uifigure('Name', 'Maze Generator-Solver',...
                      'Position', obj.DefaultFigPose, ...
                      'AutoResizeChildren',  'off', ...
                      'WindowButtonMotionFcn', @(src, event)obj.WindowSize());
            end 
            function InitGenParameters(obj) % init the parameters of the generation panel
                obj.Height = 2;
                obj.Width = 2;
                obj.GenStartPose = [1, 1];
           
            end
            function CreateGenerationPanel(obj) % creates the Generation panel

                obj.GenPanel = uipanel('Parent',obj.RunWindow, ...
                       'Title', 'Generatation panel', ...
                       'Position',[10, obj.DefaultFigPose(4) - 210, (obj.DefaultFigPose(3)-30)/2,  200], ...
                       'TitlePosition', 'centertop', ...
                       'FontSize', 14, ...
                       'FontWeight', 'bold', ...
                       'BackgroundColor','white');      
               obj.GenSubPanelSizes = uipanel('Parent',  obj.GenPanel, ...
                       'Title', 'Maze sizes', ...
                       'Position',[120, 90, 130,  80], ...
                       'TitlePosition', 'centertop', ...
                       'FontSize', 14, ...
                       'FontWeight', 'bold', ...
                       'BackgroundColor','white');
                obj.GenSubPanelStartPose = uipanel('Parent',  obj.GenPanel, ...
                       'Title', 'Start Pose', ...
                       'Position',[120, 5, 130,  80], ...
                       'TitlePosition', 'centertop', ...
                       'FontSize', 14, ...
                       'FontWeight', 'bold', ...
                       'BackgroundColor','white');
               obj.GenButton = uibutton(obj.GenPanel, 'Text', 'Generate', ...
                    'Position',[20,60,70, 50], ...
                    'FontWeight', 'bold', ...
                    'FontSize', 14, ...
                    'ButtonPushedFcn', @(src, event)obj.RunGeneration());
                
                  obj.HeigthTextArea =  uieditfield(obj.GenSubPanelSizes,'numeric',...
                      'Value', 2,...
                      'Position',[10, 10, 40, 25],...
                      'Limits', obj.DefaultSizeLimits,...
                      'LowerLimitInclusive','on',...
                      'UpperLimitInclusive','on',...
                      'RoundFractionalValues','on', ...
                      'ValueChangedFcn',@(txt,event) obj.HeightChanged(event),...
                      'FontSize', 14);
               obj.HeightLabel = uilabel( obj.GenSubPanelSizes,  'Position', [10, 32, 50, 25], 'Text', 'Height', 'FontSize', 14);

               
               obj.WidthTextArea = uieditfield(obj.GenSubPanelSizes,'numeric',...
                      'Value', 2,...
                      'Position', [65, 10, 40, 25],...
                      'Limits', obj.DefaultSizeLimits,...
                      'LowerLimitInclusive','on',...
                      'UpperLimitInclusive','on',...
                      'RoundFractionalValues','on', ...
                      'ValueChangedFcn',@(txt,event) obj.WidthChanged(event),...
                      'FontSize', 14);
               obj.WidthLabel = uilabel( obj.GenSubPanelSizes,  'Position', [65, 32, 50, 25], 'Text', 'Width', 'FontSize', 14);
              
               
                obj.GenStartRow= uieditfield(obj.GenSubPanelStartPose,'numeric',...
                      'Value', 1,...
                      'Position', [10, 10, 40, 25],...
                      'Limits', [1, obj.Height],...
                      'LowerLimitInclusive','on',...
                      'UpperLimitInclusive','on',...
                      'RoundFractionalValues','on', ...
                      'ValueChangedFcn',@(txt,event) obj.StartRowGenChanged(event),...
                      'FontSize', 14);
               
               
               
              obj.SProwLabel = uilabel(obj.GenSubPanelStartPose,  'Position', [10, 32, 50, 25], 'Text', 'Row', 'FontSize', 14);
             
             obj.GenStartCol = uieditfield(obj.GenSubPanelStartPose,'numeric',...
                      'Value', 1,...
                      'Position', [65, 10, 40, 25],...
                      'Limits', [1, obj.Width],...
                      'LowerLimitInclusive','on',...
                      'UpperLimitInclusive','on',...
                      'RoundFractionalValues','on', ...
                      'ValueChangedFcn',@(txt,event) obj.StartColGenChanged(event),...
                      'FontSize', 14);
             obj.SPcolLabel = uilabel(obj.GenSubPanelStartPose,  'Position', [65, 32, 50, 25], 'Text', 'Column', 'FontSize', 14);
              obj.GenVizCheckBox =uicheckbox(obj.GenPanel, 'Text', 'Vizualization', ...
                    'Position',[275,100,150, 50], ...
                    'FontWeight', 'bold', ...
                    'FontSize', 14, ...
                     'ValueChangedFcn', @(src, event)obj.GenVizCheckboxStatus());
             obj.StopButton = uibutton(obj.GenPanel, 'Text', 'STOP', ...
                    'Position',[300,30,60, 60], ...
                    'FontWeight', 'bold', ...
                    'FontSize', 14);
         
            end


            function  CreateSolvingPanel(obj)  % creates the Solving panel
                  obj.SolvePanel = uipanel('Parent',obj.RunWindow, ...
                       'Title', 'Solving panel', ...
                       'Position',[20+obj.GenPanel.Position(3), obj.DefaultFigPose(4) - 210, obj.GenPanel.Position(3), 200], ...
                       'TitlePosition', 'centertop', ...
                       'FontSize', 14, ...
                       'FontWeight', 'bold', ...
                       'BackgroundColor','white');


                    obj.SolveSubPanelStart = uipanel('Parent',   obj.SolvePanel, ...
                       'Title', 'Start Cell', ...
                       'Position',[120, 90, 130,  80], ...
                       'TitlePosition', 'centertop', ...
                       'FontSize', 14, ...
                       'FontWeight', 'bold', ...
                       'BackgroundColor','white');
                obj.SolveSubPanelGoal = uipanel('Parent',  obj.SolvePanel, ...
                       'Title', 'Goal Cell', ...
                       'Position',[120, 5, 130,  80], ...
                       'TitlePosition', 'centertop', ...
                       'FontSize', 14, ...
                       'FontWeight', 'bold', ...
                       'BackgroundColor','white');
               obj.SolveButton = uibutton( obj.SolvePanel, 'Text', 'Solve', ...
                    'Position',[20,60,70, 50], ...
                    'FontWeight', 'bold', ...
                    'FontSize', 14);

              obj.StRowTextArea  = uitextarea(obj.SolveSubPanelStart , 'Value', '1', ...
                       'Position', [10, 10, 40, 25], ...
                       'FontSize', 14); 
                obj.StRowLabel = uilabel(obj.SolveSubPanelStart,  'Position', [10, 32, 50, 25], 'Text', 'Row', 'FontSize', 14);


                obj.StColTextArea  = uitextarea(obj.SolveSubPanelStart  , 'Value', '1', ...
                       'Position', [65, 10, 40, 25], ...
                       'FontSize', 14); 
               obj.StColLabel = uilabel(obj.SolveSubPanelStart,  'Position', [65, 32, 50, 25], 'Text', 'Column', 'FontSize', 14);


              obj.GoalRow =    uitextarea(obj.SolveSubPanelGoal , 'Value', '1', ...
                       'Position', [10, 10, 40, 25], ...
                       'FontSize', 14); 
              obj.GoalRowLabel = uilabel(  obj.SolveSubPanelGoal ,  'Position', [10, 32, 50, 25], 'Text', 'Row', 'FontSize', 14);
              obj.GoalCol=  uitextarea(  obj.SolveSubPanelGoal  , 'Value', '1', ...
                       'Position', [65, 10, 40, 25], ...
                       'FontSize', 14); 
              obj.GoalColLabel = uilabel(  obj.SolveSubPanelGoal ,  'Position', [65, 32, 50, 25], 'Text', 'Column', 'FontSize', 14);
              obj.SolveVizCheckBox =uicheckbox(obj.SolvePanel , 'Text', 'Vizualization', ...
                    'Position',[275,100,150, 50], ...
                    'FontWeight', 'bold', ...
                    'FontSize', 14);
             obj.SolveStopButton = uibutton(obj.SolvePanel , 'Text', 'STOP', ...
                    'Position',[300,30,60, 60], ...
                    'FontWeight', 'bold', ...
                    'FontSize', 14);

            end

            
            function WindowSize(obj) % Update panels sizes
                 obj.GenPanel.Position  = [10, obj.RunWindow.Position(4) - 210, (obj.RunWindow.Position(3)-30)/2, 200]; 
                 obj.SolvePanel.Position =  [20+obj.GenPanel.Position(3), obj.RunWindow.Position(4) - 210,  obj.GenPanel.Position(3), 200];
                 obj.HeightLabel.Position(1)=  obj.HeigthTextArea.Position(3)/2 -10;
                 obj.WidthLabel.Position(1) =  obj.WidthTextArea.Position(3)/2 +  obj.WidthTextArea.Position(1) -20;
                 obj.SProwLabel.Position(1) =   obj.HeightLabel.Position(1)
                 obj.SPcolLabel.Position(1) = obj.WidthLabel.Position(1)
            end
            function HeightChanged(obj, event)
                obj.Height = event.Value;
                obj.GenStartRow.Limits = [1, obj.Height];
            end 
            function WidthChanged(obj, event)
                obj.Width = event.Value;
                obj.GenStartCol.Limits = [1, obj.Width];
            end 
            function StartRowGenChanged(obj, event)
                obj.GenStartPose(1) = event.Value;
            end 
            function StartColGenChanged(obj, event)
                obj.GenStartPose(2) = event.Value;
            end 
            function RunGeneration(obj)
                children = get(obj.GenPanel,'Children');
                 set(children(isprop(children,'Enable')),'Enable','off')
                clf
                 maze = InitMaze(obj.Height, obj.Width, obj.GenStartPose) 
                VizualizeMaze(maze, [])
                generated_maze = Randomized_DFS(maze, obj.isVizualizeGen )
                set(children(isprop(children,'Enable')),'Enable','on')
                clf
                VizualizeMaze(generated_maze, [])
                       
    
            end
            function GenVizCheckboxStatus(obj)
                obj.isVizualizeGen = obj.GenVizCheckBox.Value;
            end
         end
    
            
 end 
       

